# Generated by Django 2.2.3 on 2019-09-11 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
                ('customer_uuid', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
